[package]
name = "risl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive", "cargo"] }
exitcode = "1.1.2"

[[bin]]
# The Risl interpreter
name = "risl"
path = "src/cli/main.rs"
